### PR TITLE
Bump version to 0.8.1

### PR DESCRIPTION
**Pull request by eriknw**

### CODE REVIEW

**Comment by eriknw** [comment]
We'll need to wait until `toolz=0.8.1` is available.

Note that we keep the build and run dependency for `toolz` as loose as possible, which is `>=0.8.0`.  `cytoolz` only uses `toolz` for the signature registry to help with introspection; see https://github.com/pytoolz/cytoolz/blob/master/cytoolz/_signatures.py .

We also now make test dependency for `toolz` explicit and specific: it should match `cytoolz.__toolz_version__`.  `cytoolz` has a whole suite of "is cytoolz like toolz" tests that are only tested for specific `toolz` versions.

I don't know if it ever makes sense to have different versions of `toolz` and `cytoolz.__toolz_version__` installed in the same environment, but I also don't know if this is *wrong* to do.  Thoughts?

**Comment by jakirkham** [comment]
Closing and reopening now that `toolz` version `0.8.1` is available.

**Comment by eriknw** [comment]
Aha, so closing and re-opening re-runs CI?  Great.  I couldn't figure out how to restart AppVeyor--I was about to push dummy commits.  Thanks again.

**Comment by jakirkham** [comment]
Yeah, that's the lazy way of doing it. Should also be possible to restart all the CIs. If you don't have permissions, please let me know.

**Pull request merged**
