### PR TITLE
Fixup the pypy patch

### LINKED ISSUE #36: Cytoolz build leading to unexpected CI failures
- [ ] I read [the conda-forge documentation](https://conda-forge.org/docs/user/introduction.html#how-can-i-install-packages-from-conda-forge) and could not find the solution for my problem there.

Issue:

Over in Dask we experienced some CI failures (xref https://github.com/dask/dask/pull/7069) which I _think_ are related to the most recent `cytoolz` build. For instance, `cytoolz=0.11.0=py38h5406a74_2` appears to be a problematic build. Unfortunately I don't have a minimal reproducer using `cytoolz`, but did post some of the output from Dask CI failures in https://github.com/dask/dask/pull/7069#discussion_r557811861. 

I see there was some recent work done by @hmaarrfk over in https://github.com/pytoolz/cytoolz/pull/149 that might be related? At least it mentions potentially crashing CPython.

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list
# packages in environment at /Users/james/miniforge3/envs/dask-hanging-ci:
#
# Name                    Version                   Build  Channel
abseil-cpp                20200923.2           h046ec9c_1    conda-forge
aiobotocore               1.2.0              pyhd3eb1b0_0
aiohttp                   3.7.3            py38h5406a74_1    conda-forge
aioitertools              0.7.1              pyhd8ed1ab_0    conda-forge
apipkg                    1.5                        py_0    conda-forge
appdirs                   1.4.4              pyh9f0ad1d_0    conda-forge
appnope                   0.1.2            py38h50d1736_1    conda-forge
arrow-cpp                 2.0.0           py38h81ee75f_16_cpu    conda-forge
asciitree                 0.3.3                      py_2    conda-forge
asn1crypto                1.4.0              pyh9f0ad1d_0    conda-forge
async-timeout             3.0.1                   py_1000    conda-forge
attrs                     20.3.0             pyhd3deb0d_0    conda-forge
aws-c-cal                 0.4.5                ha1a74bd_4    conda-forge
aws-c-common              0.4.65               h35c211d_0    conda-forge
aws-c-event-stream        0.2.6                h142b3dd_1    conda-forge
aws-c-io                  0.8.0                h3654196_0    conda-forge
aws-checksums             0.1.10               h3654196_2    conda-forge
aws-sam-translator        1.32.0             pyhd3deb0d_0    conda-forge
aws-sdk-cpp               1.8.122              hd5fcc58_0    conda-forge
aws-xray-sdk              0.95                       py_0    conda-forge
backcall                  0.2.0              pyh9f0ad1d_0    conda-forge
backports                 1.0                        py_2    conda-forge
backports.functools_lru_cache 1.6.1                      py_0    conda-forge
backports.tempfile        1.0                        py_0    conda-forge
backports.weakref         1.0.post1       py38h32f6830_1002    conda-forge
bcolz                     1.2.1           py38h4f17bb1_1001    conda-forge
blosc                     1.21.0               h046ec9c_0    conda-forge
bokeh                     2.2.3            py38h50d1736_0    conda-forge
boto                      2.49.0                     py_0    conda-forge
boto3                     1.16.54            pyhd8ed1ab_0    conda-forge
botocore                  1.19.55            pyhd8ed1ab_0    conda-forge
brotli                    1.0.9                h046ec9c_4    conda-forge
brotlipy                  0.7.0           py38h5406a74_1001    conda-forge
brunsli                   0.1                  h046ec9c_0    conda-forge
bzip2                     1.0.8                hc929b4f_4    conda-forge
c-ares                    1.17.1               hc929b4f_0    conda-forge
ca-certificates           2020.12.5            h033912b_0    conda-forge
cached-property           1.5.1                      py_0    conda-forge
cachey                    0.2.1              pyh9f0ad1d_0    conda-forge
certifi                   2020.12.5        py38h50d1736_1    conda-forge
cffi                      1.14.4           py38h979bc6b_1    conda-forge
cfn-lint                  0.44.3           py38h50d1736_1    conda-forge
chardet                   3.0.4           py38h5347e94_1008    conda-forge
charls                    2.2.0                h046ec9c_0    conda-forge
chest                     0.2.3                      py_2    conda-forge
click                     7.1.2              pyh9f0ad1d_0    conda-forge
cloudpickle               1.6.0                      py_0    conda-forge
cookies                   2.2.1                      py_0    conda-forge
coverage                  5.3.1            py38h5406a74_1    conda-forge
crick                     0.0.3           py38h174b24a_1001    conda-forge
cryptography              3.3.1            py38h6b4ec92_1    conda-forge
curl                      7.71.1               hcb81553_8    conda-forge
cycler                    0.10.0                     py_2    conda-forge
cytoolz                   0.11.0           py38h5406a74_2    conda-forge
dask                      2020.12.0+48.gba9896d8.dirty           dev_0    <develop>
decorator                 4.4.2                      py_0    conda-forge
distributed               2020.12.0        py38h50d1736_0    conda-forge
docker-py                 4.4.1            py38h50d1736_0    conda-forge
docker-pycreds            0.4.0                      py_0    conda-forge
ecdsa                     0.16.1             pyhd8ed1ab_0    conda-forge
execnet                   1.7.1                      py_0    conda-forge
fasteners                 0.14.1                     py_3    conda-forge
fastparquet               0.5.0            py38hc7193ba_0    conda-forge
flask                     1.1.2              pyh9f0ad1d_0    conda-forge
freetype                  2.10.4               h4cff582_1    conda-forge
fsspec                    0.8.5              pyhd8ed1ab_0    conda-forge
future                    0.18.2           py38h50d1736_3    conda-forge
gflags                    2.2.2             hb1e8313_1004    conda-forge
giflib                    5.2.1                hbcb3906_2    conda-forge
glog                      0.4.0                hb7f4fc5_3    conda-forge
graphviz                  2.42.3               h98dfb87_0    conda-forge
grpc-cpp                  1.34.1               h1671c54_0    conda-forge
h5py                      3.1.0           nompi_py38h5142359_100    conda-forge
hdf5                      1.10.6          nompi_hc5d9132_1114    conda-forge
heapdict                  1.0.1                      py_0    conda-forge
httpretty                 1.0.5              pyhd8ed1ab_0    conda-forge
icu                       68.1                 h74dc148_0    conda-forge
idna                      2.8                   py38_1000    conda-forge
imagecodecs               2021.1.11        py38hb15f0e6_1    conda-forge
imageio                   2.9.0                      py_0    conda-forge
importlib-metadata        3.4.0            py38h50d1736_0    conda-forge
importlib_metadata        3.4.0                hd8ed1ab_0    conda-forge
iniconfig                 1.1.1              pyh9f0ad1d_0    conda-forge
ipython                   7.19.0           py38h9bb44b7_1    conda-forge
ipython_genutils          0.2.0                      py_1    conda-forge
itsdangerous              1.1.0                      py_0    conda-forge
jedi                      0.17.2           py38h50d1736_1    conda-forge
jinja2                    2.11.2             pyh9f0ad1d_0    conda-forge
jmespath                  0.10.0             pyh9f0ad1d_0    conda-forge
joblib                    1.0.0              pyhd8ed1ab_0    conda-forge
jpeg                      9d                   hbcb3906_0    conda-forge
jsondiff                  1.1.2                      py_0    conda-forge
jsonpatch                 1.24                       py_0    conda-forge
jsonpickle                1.4.1              pyh9f0ad1d_0    conda-forge
jsonpointer               2.0                        py_0    conda-forge
jsonschema                3.2.0                      py_2    conda-forge
junit-xml                 1.9                pyh9f0ad1d_0    conda-forge
jxrlib                    1.1                  h35c211d_2    conda-forge
kiwisolver                1.3.1            py38hd9c93a9_1    conda-forge
krb5                      1.17.2               h60d9502_0    conda-forge
lcms2                     2.11                 h11f7e16_1    conda-forge
lerc                      2.2.1                h046ec9c_0    conda-forge
libaec                    1.0.4                h046ec9c_1    conda-forge
libblas                   3.9.0                7_openblas    conda-forge
libcblas                  3.9.0                7_openblas    conda-forge
libcurl                   7.71.1               h9bf37e3_8    conda-forge
libcxx                    11.0.0               h4c3b8ed_1    conda-forge
libdeflate                1.7                  h35c211d_4    conda-forge
libedit                   3.1.20191231         h0678c8f_2    conda-forge
libev                     4.33                 haf1e3a3_1    conda-forge
libevent                  2.1.10               hddc9c9b_3    conda-forge
libffi                    3.3                  h046ec9c_2    conda-forge
libgfortran               5.0.0           9_3_0_h6c81a4c_16    conda-forge
libgfortran5              9.3.0               h6c81a4c_16    conda-forge
libiconv                  1.16                 haf1e3a3_0    conda-forge
liblapack                 3.9.0                7_openblas    conda-forge
libllvm10                 10.0.1               h009f743_3    conda-forge
libnghttp2                1.41.0               h7580e61_2    conda-forge
libopenblas               0.3.12          openmp_h54245bb_1    conda-forge
libpng                    1.6.37               h7cec526_2    conda-forge
libprotobuf               3.14.0               hfd3ada9_0    conda-forge
libssh2                   1.9.0                h8a08a2b_5    conda-forge
libthrift                 0.13.0               h990abc0_6    conda-forge
libtiff                   4.2.0                h355d032_0    conda-forge
libutf8proc               2.6.1                h35c211d_0    conda-forge
libwebp-base              1.1.0                hbcb3906_3    conda-forge
libxml2                   2.9.10               h802ca4f_3    conda-forge
libxslt                   1.1.33               h5739fc3_2    conda-forge
libzopfli                 1.0.3                h046ec9c_0    conda-forge
llvm-openmp               11.0.0               h73239a0_1    conda-forge
llvmlite                  0.35.0           py38hc583f44_1    conda-forge
locket                    0.2.0                      py_2    conda-forge
lxml                      4.6.2            py38h7d97eb6_1    conda-forge
lz4                       3.1.1            py38hdb231c4_1    conda-forge
lz4-c                     1.9.3                h046ec9c_0    conda-forge
markupsafe                1.1.1            py38h5406a74_3    conda-forge
matplotlib-base           3.3.3            py38hdcc317e_0    conda-forge
mmh3                      2.5.1            py38h0a5c65b_3    conda-forge
mock                      4.0.2            py38h32f6830_1    conda-forge
monotonic                 1.5                        py_0    conda-forge
more-itertools            8.6.0              pyhd8ed1ab_0    conda-forge
moto                      1.3.16             pyhd8ed1ab_1    conda-forge
msgpack-python            1.0.2            py38hd9c93a9_1    conda-forge
multidict                 5.1.0            py38h5406a74_1    conda-forge
ncurses                   6.2                  h2e338ed_4    conda-forge
networkx                  2.5                        py_0    conda-forge
numba                     0.52.0           py38he9f00de_0    conda-forge
numcodecs                 0.7.2            py38h3289252_1    conda-forge
numexpr                   2.7.2            py38he9f00de_0    conda-forge
numpy                     1.17.5           py38h6ced74f_1    conda-forge
olefile                   0.46               pyh9f0ad1d_1    conda-forge
openjpeg                  2.4.0                h6cbf5cd_0    conda-forge
openssl                   1.1.1i               h35c211d_0    conda-forge
orc                       1.6.6                h675e114_1    conda-forge
packaging                 20.8               pyhd3deb0d_0    conda-forge
pandas                    1.0.5            py38h5fc983b_0    conda-forge
pandas-datareader         0.8.1                      py_0    conda-forge
parquet-cpp               1.5.1                         2    conda-forge
parso                     0.7.1              pyh9f0ad1d_0    conda-forge
partd                     1.1.0                      py_0    conda-forge
pexpect                   4.8.0              pyh9f0ad1d_2    conda-forge
pickleshare               0.7.5                   py_1003    conda-forge
pillow                    8.1.0            py38hc1d52f7_1    conda-forge
pip                       20.3.3             pyhd8ed1ab_0    conda-forge
pluggy                    0.13.1           py38h50d1736_4    conda-forge
pooch                     1.3.0              pyhd8ed1ab_0    conda-forge
prompt-toolkit            3.0.10             pyha770c72_0    conda-forge
psutil                    5.8.0            py38h5406a74_1    conda-forge
ptyprocess                0.7.0              pyhd3deb0d_0    conda-forge
py                        1.10.0             pyhd3deb0d_0    conda-forge
pyarrow                   2.0.0           py38h8315e4b_16_cpu    conda-forge
pycparser                 2.20               pyh9f0ad1d_2    conda-forge
pygments                  2.7.3              pyhd8ed1ab_0    conda-forge
pyopenssl                 20.0.1             pyhd8ed1ab_0    conda-forge
pyparsing                 2.4.7              pyh9f0ad1d_0    conda-forge
pyrsistent                0.17.3           py38h5406a74_2    conda-forge
pysocks                   1.7.1            py38h50d1736_3    conda-forge
pytables                  3.6.1            py38hfb086ad_3    conda-forge
pytest                    6.2.1            py38h50d1736_1    conda-forge
pytest-forked             1.2.0              pyh9f0ad1d_0    conda-forge
pytest-timeout            1.4.2                    pypi_0    pypi
pytest-xdist              2.2.0              pyhd8ed1ab_0    conda-forge
python                    3.8.6           h624753d_4_cpython    conda-forge
python-dateutil           2.8.1                      py_0    conda-forge
python-graphviz           0.16               pyhd3deb0d_1    conda-forge
python-jose               3.1.0              pyh9f0ad1d_0    conda-forge
python-snappy             0.5.4            py38he547acd_3    conda-forge
python-xxhash             2.0.0            py38h5406a74_1    conda-forge
python_abi                3.8                      1_cp38    conda-forge
pytz                      2020.5             pyhd8ed1ab_0    conda-forge
pywavelets                1.1.1            py38hc7193ba_3    conda-forge
pyyaml                    5.3.1            py38h5406a74_2    conda-forge
re2                       2020.11.01           h2e338ed_0    conda-forge
readline                  8.0                  h0678c8f_2    conda-forge
requests                  2.25.1             pyhd3deb0d_0    conda-forge
responses                 0.12.1             pyhd3deb0d_0    conda-forge
s3fs                      0.5.2              pyhd8ed1ab_0    conda-forge
s3transfer                0.3.4              pyhd8ed1ab_0    conda-forge
scikit-image              0.18.1           py38he9f00de_0    conda-forge
scikit-learn              0.24.0           py38hfd19401_0    conda-forge
scipy                     1.6.0            py38h95ea19e_0    conda-forge
setuptools                49.6.0           py38h50d1736_3    conda-forge
six                       1.15.0             pyh9f0ad1d_0    conda-forge
snappy                    1.1.8                hb1e8313_3    conda-forge
sortedcontainers          2.3.0              pyhd8ed1ab_0    conda-forge
sparse                    0.11.2                     py_0    conda-forge
sqlalchemy                1.3.22           py38h5406a74_1    conda-forge
sqlite                    3.34.0               h17101e1_0    conda-forge
sshpubkeys                3.1.0                      py_0    conda-forge
tblib                     1.6.0                      py_0    conda-forge
threadpoolctl             2.1.0              pyh5ca1d4c_0    conda-forge
thrift                    0.11.0          py38h4a8c4bd_1001    conda-forge
tifffile                  2021.1.11          pyhd8ed1ab_0    conda-forge
tiledb                    2.1.6                h6a9efa5_1    conda-forge
tiledb-py                 0.7.5            py38h94eedbb_0    conda-forge
tk                        8.6.10               h0419947_1    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
toolz                     0.11.1                     py_0    conda-forge
tornado                   6.1              py38h5406a74_1    conda-forge
traitlets                 5.0.5                      py_0    conda-forge
typing-extensions         3.7.4.3                       0    conda-forge
typing_extensions         3.7.4.3                    py_0    conda-forge
urllib3                   1.26.2             pyhd8ed1ab_0    conda-forge
wcwidth                   0.2.5              pyh9f0ad1d_2    conda-forge
websocket-client          0.57.0           py38h50d1736_4    conda-forge
werkzeug                  1.0.1              pyh9f0ad1d_0    conda-forge
wheel                     0.36.2             pyhd3deb0d_0    conda-forge
wrapt                     1.12.1           py38h5406a74_3    conda-forge
xmltodict                 0.12.0                     py_0    conda-forge
xxhash                    0.8.0                h35c211d_3    conda-forge
xz                        5.2.5                haf1e3a3_1    conda-forge
yaml                      0.2.5                haf1e3a3_0    conda-forge
yarl                      1.6.3            py38h5406a74_1    conda-forge
zarr                      2.6.1              pyhd8ed1ab_0    conda-forge
zfp                       0.5.5                h046ec9c_4    conda-forge
zict                      2.0.0                      py_0    conda-forge
zipp                      3.4.0                      py_0    conda-forge
zlib                      1.2.11            h7795811_1010    conda-forge
zstd                      1.4.8                hf387650_1    conda-forge
```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info
     active environment : dask-hanging-ci
    active env location : /Users/james/miniforge3/envs/dask-hanging-ci
            shell level : 3
       user config file : /Users/james/.condarc
 populated config files : /Users/james/miniforge3/.condarc
          conda version : 4.8.3
    conda-build version : not installed
         python version : 3.7.6.final.0
       virtual packages : __osx=10.16
       base environment : /Users/james/miniforge3  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/osx-64
                          https://conda.anaconda.org/conda-forge/noarch
          package cache : /Users/james/miniforge3/pkgs
                          /Users/james/.conda/pkgs
       envs directories : /Users/james/miniforge3/envs
                          /Users/james/.conda/envs
               platform : osx-64
             user-agent : conda/4.8.3 requests/2.23.0 CPython/3.7.6 Darwin/20.2.0 OSX/10.16
                UID:GID : 501:20
             netrc file : None
           offline mode : False
```
</details>

### PR DESCRIPTION
**Pull request by hmaarrfk**
@mattip 
Closes #36
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by hmaarrfk** [comment]
cc: @jrbourbeau 

@conda-forge/cytoolz would you rather we only apply these patches for pypy?

**Comment by jakirkham** [comment]
Either way seems fine. Suppose limiting it to PyPy wouldn't disrupt CPython builds, which makes sense given the recent issue

**Comment by jakirkham** [comment]
It appears the macOS test suite is segfaulting though. Do we have any thoughts as to why?

cc @mattip (in case you have thoughts)

**Comment by eriknw** [comment]
LGTM (but no idea about the test suite segfault).

**Comment by hmaarrfk** [comment]
We fixed up tuple issues.

This seems to be one relating to lists

**Comment by hmaarrfk** [comment]
not too sure why osx is working now. but it is ....

**Comment by jakirkham** [comment]
Well let's try it. If we see issues crop up, we can handle them independently.

**Comment by jakirkham** [comment]
FWIW no issues showed up on `master` when building these packages.

**Pull request merged**
